# Generated by Django 2.2.5 on 2019-09-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190930_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Infomations', 'verbose_name_plural': 'User Infomations'},
        ),
    ]
