# Generated by Django 2.2.5 on 2019-09-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190930_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户信息表', 'verbose_name_plural': '用户信息表'},
        ),
    ]
