# Generated by Django 2.2.5 on 2019-09-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190930_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
