# Generated by Django 2.2 on 2019-04-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('weeklyNumber', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='weeklyNumber')),
                ('timeLimit', models.CharField(max_length=64, verbose_name='timeLimit')),
                ('weeklySubmit', models.CharField(choices=[('0', 'Enable'), ('1', 'Disable')], max_length=1, verbose_name='weeklySubmit')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('company_name', models.CharField(choices=[('C0001', '北京中科云链信息技术有限公司'), ('C0002', '北京合力中税信息技术有限公司')], max_length=1, verbose_name='company')),
                ('department', models.CharField(choices=[('D0001', '产品部'), ('D0002', '开发部'), ('D0003', '运维部'), ('D0004', '信息技术部'), ('D0003', '其他')], max_length=1, verbose_name='department')),
                ('role', models.CharField(choices=[('R0001', '管理员'), ('R0002', '公司领导'), ('R0003', '部门领导'), ('R0004', '公司职员')], max_length=1, verbose_name='role')),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='username')),
                ('email', models.CharField(max_length=500, verbose_name='email')),
                ('password', models.CharField(default='A111111', max_length=64, verbose_name='password')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeklyNumber', models.CharField(max_length=40, verbose_name='weeklyNumber')),
                ('timeLimit', models.CharField(max_length=64, verbose_name='timeLimit')),
                ('department', models.CharField(max_length=100, verbose_name='department')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('local_weeky', models.CharField(max_length=500, verbose_name='本周工作')),
                ('next_plan', models.CharField(max_length=500, verbose_name='下周计划')),
                ('exist_problem', models.CharField(max_length=500, verbose_name='存在问题')),
            ],
            options={
                'db_table': 'Weekly',
                'unique_together': {('weeklyNumber', 'timeLimit', 'username')},
            },
        ),
    ]
