# Generated by Django 2.2 on 2019-05-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_app', '0002_auto_20190429_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=64, verbose_name='ProjectNumber')),
                ('project_name', models.CharField(max_length=128, verbose_name='ProjectName')),
                ('project_start_time', models.DateField(verbose_name='ProjectStartTime')),
                ('project_end_time', models.DateField(verbose_name='ProjectEndTime')),
            ],
            options={
                'db_table': 'my_project',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('R0001', '职员'), ('R0002', '部门领导'), ('R0003', '领导'), ('R0004', '管理员')], max_length=1, verbose_name='role'),
        ),
    ]
