# Generated by Django 2.2 on 2019-05-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_app', '0003_auto_20190505_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='ProjectNumber'),
        ),
    ]
