# Generated by Django 2.2 on 2019-05-07 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_app', '0004_auto_20190506_1628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Config',
            new_name='ConfigWeekly',
        ),
    ]
