# Generated by Django 2.2 on 2019-05-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_app', '0005_auto_20190507_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeklyNumber', models.CharField(max_length=40, verbose_name='weeklyNumber')),
                ('timeLimit', models.CharField(max_length=64, verbose_name='timeLimit')),
                ('department', models.CharField(max_length=100, verbose_name='department')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('work_this_week', models.CharField(max_length=500, verbose_name='本周工作')),
                ('next_week_plan', models.CharField(max_length=500, verbose_name='下周计划')),
                ('problems_in_work', models.CharField(max_length=500, verbose_name='存在问题')),
            ],
            options={
                'db_table': 'weekly_records',
                'unique_together': {('weeklyNumber', 'timeLimit', 'department', 'username')},
            },
        ),
    ]
