# Generated by Django 2.2 on 2019-08-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_app', '0007_auto_20190520_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyrecords',
            name='weekly_submit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='提交时间'),
        ),
    ]
