# Generated by Django 2.2.5 on 2019-09-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0002_auto_20190923_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_start_time',
            new_name='start_date',
        ),
    ]
