# Generated by Django 2.2.5 on 2019-09-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0003_auto_20190923_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyConf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weekly_no', models.CharField(max_length=32)),
                ('weekly_cycle', models.CharField(max_length=64)),
                ('create_no_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weekly_conf',
            },
        ),
        migrations.CreateModel(
            name='WeeklyInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weekly_cycle', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=64)),
                ('completed_in_this_week', models.TextField()),
                ('working_plan_for_next_week', models.TextField()),
                ('new_issue', models.TextField()),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weekly_info',
            },
        ),
    ]
