# Generated by Django 2.2.5 on 2019-09-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0005_auto_20190925_1529'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='confweekly',
            table='conf_weekly',
        ),
    ]
